#!/usr/bin/env bash
# Configuring my WebServer and Making my first Get Request

# Install Nginx
apt-get install -y nginx

# adding my Message
echo "Hello World!" >/var/www/html/index.html

# Starting my WebServer
service nginx start
