#!/usr/bin/env bash
# Making A redirection Page

apt-get update

# Install Nginx
apt-get install -y nginx

# Stoping my Service to configure
service nginx stop

file="/etc/nginx/sites-available/default"
target="https://www.youtube.com/watch?v=QH2-TGUlwu4"

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 $target;
    }
}" >$file

# sed -i "/server_name _;/a \
# location /redirect_me { \
# return 301 $target; \
# }" $file

# adding my Message
touch /var/www/html/index.html
echo "Hello World!" >/var/www/html/index.html

# Starting my WebServer
service nginx start
