#!/usr/bin/env bash
# Making A redirection Page

apt-get update

# Install Nginx
apt-get install -y nginx

# Stoping my Service to configure
service nginx stop

file="/etc/nginx/sites-available/default"
target="https://www.youtube.com/watch?v=QH2-TGUlwu4"

sed -i "/server_name _;/a \
location /redirect_me { \
return 301 $target; \
}" $file

# adding my Message
echo "Hello World!" >/var/www/html/index.html

# Starting my WebServer
service nginx start
