#!/usr/bin/env bash

apt-get update

# Install Nginx
apt-get install -y nginx

# Stoping my Service to configure
service nginx stop

file="/etc/nginx/sites-available/default"
target="https://www.youtube.com/watch?v=QH2-TGUlwu4"

sed -i "/location \/ {/a \\\n\treturn 301 $target;" $file

# adding my Message
echo "Hello World!" >/var/www/html/index.html

# Starting my WebServer
service nginx start
