#!/usr/bin/env bash
# Making my not found Default Page

apt-get update

# Install Nginx
apt-get install -y nginx

# Stoping my Service to configure
service nginx stop

path="/etc/nginx/sites-available/default"
target="https://www.youtube.com/watch?v=QH2-TGUlwu4"
touch /var/www/html/404.html
echo "Ceci n'est pas une page" >/var/www/html/404.html


printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 $target;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > $path


# sed -i "/server_name _;/a \
# error_page 404 /404.html; \
# location /404 { \
# root /var/www/html; \
# internal; \
# }" $path

# sed -i "/server_name _;/a \
# location /redirect_me { \
# return 301 $target; \
# }" $path

# Starting my WebServer
service nginx start
