#!/usr/bin/env bash
path='/etc/nginx/sites-available/default'
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "/server_name _;/a \
    error_page 404 /404.html; \
    location /404 { \
        alias /var/www/html/404.html; \
        internal; \
        return 404; \
    }" $path

sudo service nginx restart
