#!/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
sudo bash -c 'cat > /etc/nginx/conf.d/custom_http_header.conf << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        add_header X-Served-By \$hostname;
    }
}
EOF'

# Restart Nginx to apply the changes
sudo systemctl restart nginx
