#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=1
while [ $count -lt 100 ]; do

    if ((count % 3 == 0)); then
        echo "Fizz"
    elif ((count % 5 == 0)); then
        echo "Buzz"
    elif ((count % 3 == 0)) && ((count % 5 == 0)); then
        echo "FizzBuzz"
    else
        echo "$count"
    fi
    count=$((count + 1))
done
