#!/usr/bin/env bash
# making a story out of the data
while IFS=: read -r usrname password usrid groupid usridinfo homedir cmd; do
    echo "The user $usrname is part of the $groupid gang, lives in $homedir and rides $cmd. $usrid's place is protected by the passcode $password, more info about the user here: $usridinfo"
done </etc/passwd
