#!/usr/bin/env bash
# configuring an Ubuntu server
k="127.0.0.2    localhost"
m="8.8.8.8  facebook.com"

cp /etc/hosts ~/hosts.new
echo "$k" >~/hosts.new
echo "$m" >>~/hosts.new
cp -f ~/hosts.new /etc/hosts
